In [1]:
import numpy as np
M1=np.array([1,2,3])
M2=np.array([4,5,6])
print(f"Array M1:{M1}\n")
print(f"Array M2:{M2}\n")
M=np.concatenate((M1,M2))
print(f"Concatenated Array: {M}")

Array M1:[1 2 3]

Array M2:[4 5 6]

Concatenated Array: [1 2 3 4 5 6]


In [2]:
a=np.array([1,2],
           [4,5],
           [6,7])
b=np.array([2,4],
           [1,5],
           [0,6])
C=np.concatenate((a,b))
print({C})

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [4]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
vertical_concat=np.concatenate((a,b), axis=0)
print("Vertical Concatenation:")
print(vertical_concat)

Vertical Concatenation:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
vertical_concat=np.concatenate((a,b), axis=1)
print("Vertical Concatenation:")
print(vertical_concat)
print("

Vertical Concatenation:
[[1 2 5 6]
 [3 4 7 8]]


In [6]:
arr=np.array([[1,2,3],[4,5,6]])
flat_arr=arr.ravel()
print(flat_arr)

[1 2 3 4 5 6]


In [7]:
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]
